services:
  postgres:
    image: postgres:16
    container_name: postgres
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    networks:
      - backend

  backend:
    image: a0xa0x/backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file: .env
    ports:
      - "4000:3001"
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - backend
      - shared

  frontend:
    image: a0xa0x/frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "8081:80"
    networks:
      - frontend
      - shared

volumes:
  postgres_data:
networks:
  backend:
  frontend:
  shared:
